### ISSUE TITLE
2021.09 - loose my config files while upgrading

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#174] opened 2021-10-08 05:44 UTC
Hello,

I've not yet found the reason but I've lost my config files folder during upgrade. I see there was a change around the rsync command for config but don't understand why it is crashed my installation.

Unfortunately I did not backup those files.

I did config manually but now I'm having issue with another config file DBstructure. Maybe nothing directly related with docker part this time. I'll continue my investigations.
EDIT: forget this second part it was a missing configuration.

**Comment by nupplaphil** [comment] 2021-10-08 10:42
That was a bug for the stable artifact :-(
I accidentally included the `local.config.php` into the archive, so the script overwrites the existing one.
You mean this PR: https://github.com/friendica/docker/pull/172 , don't you? This covers the issue, but the root cause is closed with this PR: https://github.com/friendica/docker/pull/173

I'm really sorry .. 

This shouldn't happen with the latest stable docker image anymore ..

**Comment by valvin1** [comment] 2021-10-08 15:34
no worries I have to do better backups ;)

it looks my instance is up again I might have lost some settings but I'll find them back in the future :)

**Comment by ThRPctmylSgltwH** [comment] 2021-10-08 19:50
I had the same issue and I edited the local.config.php file and reentered all entries in the database section. The container is now up but when I connect to the web interface to login I receive this error.
```
Fatal error: Uncaught Exception: Missing database structure config file static/dbstructure.config.php in /var/www/html/src/Database/DBStructure.php:306 Stack trace: #0 /var/www/html/src/Database/Database.php(87): Friendica\Database\DBStructure::definition('/vagrant', false) #1 [internal function]: Friendica\Database\Database->__construct(Object(Friendica\Core\Config\Cache), Object(Friendica\Util\Profiler), Object(Psr\Log\NullLogger)) #2 /var/www/html/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs(Object(Friendica\Database\Database), Array) #3 /var/www/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}(Array, Array) #4 /var/www/html/vendor/level-2/dice/Dice.php(247): Dice\Dice->create('Friendica\\Datab...', Array, Array) #5 /var/www/html/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}(Array, Array) #6 /var/www/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}(Array, Array) #7 /var/www/html/src/DI.php(62): Dice\Dice->create('Friendica\\App') #8 /var/www/html/index.p in /var/www/html/src/Database/DBStructure.php on line 306
```
Is there a fix for this?
I have pulled the latest image just a few minutes ago.

**Comment by valvin1** [comment] 2021-10-08 20:09
I had the same issue. It is the system base path which should correspond to the main folder. In our case /var/www/html
Hope it'll help.

**Comment by ThRPctmylSgltwH** [comment] 2021-10-08 20:12
Thank you. That did it and I am back in.

**Comment by nupplaphil** [comment] 2021-10-08 20:13
Where did you set this config @valvin1. Normally the basepath shouldn't be set manually for Docker, because it uses standard directories for it

**Comment by ThRPctmylSgltwH** [comment] 2021-10-08 20:14
I set it in local.config.php and no restart was even required. It just worked. The original value was 'basepath' => 'vagrant', and I changed it to 'basepath' => '/var/www/html',

**Comment by nupplaphil** [comment] 2021-10-08 20:18
örks .. that's a leftover from the `local.config.php` issue, it's the basepath of my local dev-environment -.-*

**Comment by ThRPctmylSgltwH** [comment] 2021-10-08 20:30
Next issue also related is I cannot start daemon.php. When logged into the container as root, error is 

root@friendica:/var/www/html# php bin/daemon.php start 
Starting worker daemon.
Child process started with pid 71.
**sh: 1: /usr/bin/php: not found**
root@friendica:/var/www/html#

The error keeps repeating and the queue does not empty in the Admin webpage.
Is this also a simple solution related to the local.config.php file?

**Comment by nupplaphil** [comment] 2021-10-08 20:35
yep ..

plz set `config.php_path` to `php`, like:
```console
root@ex52 /opt/docker/friendica # docker-compose exec --user=www-data app php bin/console.php config config php_path php
config.php_path <= php
```

**Comment by ThRPctmylSgltwH** [comment] 2021-10-08 20:52
That fixed it for now. I will post any further errors but I am hoping to not have any. Have a nice evening.

**Comment by nupplaphil** [comment] 2021-10-08 20:54
I hope so too :-/ thanks for your patience

**Comment by nupplaphil** [comment] 2021-11-18 22:31
closed since no further errors I guess :-)

**Closed as completed by nupplaphil** 2021-11-18 22:31 UTC
Labels: Bug

**Comment by valvin1** [comment] 2021-11-19 06:21
yes sorry I forgot to give news on my side. but i'm wondering if I updated the image after fixing errors. I'll try and let you know.

**Comment by ThRPctmylSgltwH** [comment] 2021-11-19 06:56
I have not seen any further errors. I am fine with the closing of this topic.
