### ISSUE TITLE
error in redis configuration - versionning change 

### ISSUE THREAD

**Issue by valvin1** [friendica/docker#196] opened 2022-02-15 08:02 UTC
hello,

unfortunately 2021.09 isn't very stable and I should remove my `imagePullPolicy: Always` configuration.

I think this [commit](https://github.com/friendica/docker/commit/6edd78174b1a6de7610146c092c7a316d435f527) introduce a new bug in my configuration.

```
Configuring Redis as session handler
/entrypoint.sh: 52: Bad substitution
```

I have net yet seen if I should update my configuration but I think it would be nice to have a sort of versionning in image tag. If I deploy a `2021.09` it should be always the same image. If I want a new feature or a fix it should be `2021.09-1` or something like this?

What do you think of this idea ?

**Comment by valvin1** [comment] 2022-02-15 19:39
i'm looking at the error itself and don't understand what is wrong. It breaks at https://github.com/friendica/docker/blob/stable/docker-entrypoint.sh#L52 and my `REDIS_HOST` is set to `friendica-redis.friendica.svc.cluster.local`

when i do the following command on my computer I don't have any issue:

```
sh-5.1$ export REDIS_HOST=friendica-redis.friendica.svc.cluster.local
sh-5.1$ echo ${REDIS_HOST:0:1}
f
```
but in the image `php:7.4-apache-bullseye`

```
podman run --rm -it --entrypoint="/bin/sh" php:7.4-apache-bullseye
# export REDIS_HOST=friendica-redis.friendica.svc.cluster.local
# echo ${REDIS_HOST:0:1}
/bin/sh: 2: Bad substitution
```

it looks to be specific to the sh version of the docker image?

**Comment by valvin1** [comment] 2022-02-15 19:47
it looks like `${REDIS_HOST:0:1}` is `bash` but we are using `sh`

i belive i was on `sh` but on my computer :

```
ls -l /usr/bin/sh
lrwxrwxrwx. 1 root root 4 26 janv.  2021 /usr/bin/sh -> bash
```

so it works with bash not sh.

**Comment by nupplaphil** [comment] 2022-02-15 22:25
@valvin1 - Please retry and close this issue after   https://github.com/docker-library/official-images/pull/11872 is merged

> 
> I have net yet seen if I should update my configuration but I think it would be nice to have a sort of versionning in image tag. If I deploy a `2021.09` it should be always the same image. If I want a new feature or a fix it should be `2021.09-1` or something like this?
> 
> What do you think of this idea ?

The problem is that the versioning follows the rules from the upstream branch.. I think it would be better to have a an CI environment here, where we/I can prove that the setup still works .. "just" building it doesn't seem to be enough

and tbh I thought it was a "quick win" because I found this (working) script at Nextcloud as well, so I didn't test it enough.. my bad :-/

**Comment by valvin1** [comment] 2022-02-16 05:57
Thank you for the fix and I let you know when my instance is up again.

The goal of this issue is more about a frozen version of the stable images. New development, quick wins shouldn't be applied to stable version directly. Maybe stable version shouldn't be published from mainstream but from a tag?

You are doing a great work but it is really frustrating having an instance which could stop working at any time when my server pulls again the stable image.

**Comment by valvin1** [comment] 2022-02-17 06:37
My instance has downloaded a new image during the night and is up again.

**Comment by nupplaphil** [comment] 2022-02-17 20:56
I opened another issue for the versioning topic #200 and close this issue because the bug per se is fixed :)

**Closed as completed by nupplaphil** 2022-02-17 20:56 UTC
Labels: Bug
